openapi: 3.0.0
info:
  version: 0.0.1
  title: Radio Station API
servers:
  - url: 'http://localhost:3000'
paths:
  /config:
    get:
      summary: 'Returns details about the current station configuration'
      operationId: getConfig
      tags:
        - config
      responses:
        '200':
          description: 'Details about the station configuration'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      summary: 'Update station configuration info'
      operationId: patchConfig
      tags:
        - config
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Config'
      responses:
        '200':
          description: 'The updated station configuration'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /authenticate:
    post:
      summary: 'Authenticate with the station (e.g. station manager)'
      operationId: postAuthenticate
      tags:
        - authenticate
      requestBody:
        description: 'Authentication credentials'
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthenticationRequest'
      responses:
        '200':
          description: 'Access token that can be used to access protected functions'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
        '401':
          description: 'Invalid credentials'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /now-playing:
    get:
      summary: 'Returns now playing info'
      operationId: getNowPlaying
      tags:
        - now playing
      responses:
        '200':
          description: 'Now playing info'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NowPlayingInfo'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      summary: 'Update now playing info'
      operationId: patchNowPlaying
      tags:
        - now playing
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 'The updated now playing info'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NowPlayingInfo'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  schemas:
    Config:
      type: object
      properties:
        streams:
          type: array
          items:
            $ref: '#/components/schemas/StationStream'
        stationWebsiteURL:
          type: string
      required:
        - streams
        - stationWebsiteURL

    StationStream:
      type: object
      properties:
        name:
          type: string
        extension:
          type: string
        bitrate:
          type: integer
        url:
          type: string
        qualityScore:
          type: integer
      required:
        - name
        - extension
        - bitrate
        - url
        - qualityScore

    AuthenticationRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password

    AuthenticationResponse:
      type: object
      properties:
        token:
          type: string
      required:
        - token

    NowPlayingInfo:
      type: object
      properties:
        showName:
          type: string
        trackTitle:
          type: string
        trackArtist:
          type: string
    
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message
