openapi: 3.0.0
info:
  version: 0.0.1
  title: Radio Station API
servers:
  - url: 'http://localhost:3000'
paths:
  /config:
    get:
      summary: 'Get station configuration info'
      operationId: getConfig
      tags:
        - config
      responses:
        '200':
          description: 'Details about the station configuration'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      summary: 'Update station configuration info'
      operationId: patchConfig
      tags:
        - config
      security:
        - BearerAuth: []
        - APIKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Config'
      responses:
        '200':
          description: 'The updated station configuration'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        '401':
          $ref: '#/components/responses/NotAuthorized'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /authenticate:
    post:
      summary: 'Authenticate with the station'
      operationId: postAuthenticate
      tags:
        - authenticate
      security:
        - APIKeyAuth: []
      requestBody:
        description: 'Authentication credentials'
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthenticationRequest'
      responses:
        '200':
          description: 'Access token that can be used to access protected functions'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
        '401':
          description: 'Invalid credentials'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /now-playing:
    get:
      summary: 'Get now playing info'
      operationId: getNowPlaying
      tags:
        - now playing
      responses:
        '200':
          description: 'Now playing info'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NowPlayingInfo'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      summary: 'Update now playing info'
      operationId: patchNowPlaying
      tags:
        - now playing
      security:
        - BearerAuth: []
        - APIKeyAuth: []
      responses:
        '200':
          description: 'The updated now playing info'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NowPlayingInfo'
        '401':
          $ref: '#/components/responses/NotAuthorized'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /shows:
    get:
      summary: 'Get list of shows'
      operationId: getShows
      tags:
        - shows
      responses:
        '200':
          description: 'Shows'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfShows'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: 'Create show'
      operationId: postShows
      tags:
        - shows
      security:
        - BearerAuth: []
        - APIKeyAuth: []
      responses:
        '201':
          description: 'The show that was created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Show'
        '401':
          $ref: '#/components/responses/NotAuthorized'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /shows/{id}:
    get:
      summary: 'Get show by ID'
      operationId: getShowById
      tags:
        - shows
      parameters:
        - name: id
          in: path
          description: 'Show ID'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'The specified show'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Show'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      summary: 'Modify show'
      operationId: patchShow
      tags:
        - shows
      security:
        - BearerAuth: []
        - APIKeyAuth: []
      parameters:
        - name: id
          in: path
          description: 'Show ID'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'The modified show'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Show'
        '401':
          $ref: '#/components/responses/NotAuthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: 'Delete show'
      operationId: deleteShow
      tags:
        - shows
      security:
        - BearerAuth: []
        - APIKeyAuth: []
      parameters:
        - name: id
          in: path
          description: 'Show ID'
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: 'Show deleted successfully'
        '401':
          $ref: '#/components/responses/NotAuthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  responses:
    NotAuthorized:
      description: 'The request is missing proper authorization'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    
    NotFound:
      description: 'The resource was not found'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
    
    APIKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

  schemas:
    Config:
      type: object
      properties:
        streams:
          type: array
          items:
            $ref: '#/components/schemas/StationStream'
        stationWebsiteURL:
          type: string
      required:
        - streams
        - stationWebsiteURL

    StationStream:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        bitrate:
          type: integer
        url:
          type: string
        qualityScore:
          type: integer
      required:
        - name
        - type
        - bitrate
        - url
        - qualityScore

    AuthenticationRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
          format: password
      required:
        - email
        - password

    AuthenticationResponse:
      type: object
      properties:
        token:
          type: string
      required:
        - token

    NowPlayingInfo:
      type: object
      properties:
        showName:
          type: string
        trackTitle:
          type: string
        trackArtist:
          type: string
    
    ArrayOfShows:
      type: array
      items:
        $ref: '#/components/schemas/Show'
    
    Show:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        facebookURL:
          type: string
        twitterURL:
          type: string
        websiteURL:
          type: string
        imageURL:
          type: string
        hosts:
          type: string
        location:
          type: string
        showTime:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        summary:
          type: string
      required:
        - id
        - name
        - imageURL
        - hosts
        - location
        - showTime
        - startTime
        - endTime
        - summary
    
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
      required:
        - code
        - message