#if !canImport(ObjectiveC)
import XCTest

extension AuthControllerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AuthControllerTests = [
        ("test_getUsersMe_authenticationFailure", test_getUsersMe_authenticationFailure),
        ("test_getUsersMe_returnsUser", test_getUsersMe_returnsUser),
        ("test_postAuthenticate_authenticationFailure", test_postAuthenticate_authenticationFailure),
        ("test_postAuthenticate_authenticationSuccess", test_postAuthenticate_authenticationSuccess),
    ]
}

extension ShowControllerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ShowControllerTests = [
        ("test_deleteShow_deletesShow", test_deleteShow_deletesShow),
        ("test_getShow_returnsShow", test_getShow_returnsShow),
        ("test_getShows_returnShows", test_getShows_returnShows),
        ("test_patchShow_updatesShow", test_patchShow_updatesShow),
        ("test_postShows_createsShow", test_postShows_createsShow),
    ]
}

extension StationConfigControllerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StationConfigControllerTests = [
        ("test_getStationConfig_returnsConfig", test_getStationConfig_returnsConfig),
        ("test_patchStationConfig_updatesConfig", test_patchStationConfig_updatesConfig),
        ("test_postStationConfig_abortsIfConfigAlreadyExists", test_postStationConfig_abortsIfConfigAlreadyExists),
        ("test_postStationConfig_createsConfig", test_postStationConfig_createsConfig),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AuthControllerTests.__allTests__AuthControllerTests),
        testCase(ShowControllerTests.__allTests__ShowControllerTests),
        testCase(StationConfigControllerTests.__allTests__StationConfigControllerTests),
    ]
}
#endif
